displayName=Gauntlet Highlighter
author=kcjg94
description=Routing and highlighting helper for the Corrupted Gauntlet
tags=gauntlet,corrupted,hunllef,route
version=1.0.0
plugins=com.kcjg94.easycgplugin.GauntletHighlighterPlugin
build=standard